{% set name = "particle" %}
{% set version = "0.15.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/particle-{{ version }}.tar.gz
  sha256: dbf00b97918b52563ae1d6597231323733229bf5d681834ed82988dcea01a48e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools_scm
  run:
    - attrs >=19.2
    - hepunits >=1.2.0
    # Only required for [py<37] but always include so this can be noarch: python
    - importlib_resources >=1.0
    - python >=3.6

test:
  imports:
    - particle
    - particle.converters
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/scikit-hep/particle
  summary: Extended PDG particle data and MC identification codes
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - chrisburr
