{% set name = "particle" %}
{% set version = "0.20.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/particle-{{ version }}.tar.gz
  sha256: 1e8596c2818cae446a958ceb1766a91acc6c6401f01db1d23b94c24827a5c547

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools_scm
  run:
    - attrs >=19.2
    - deprecated
    - hepunits >=2.0.0
    - importlib_resources >=2.0
    - python >=3.6
    - typing-extensions

test:
  imports:
    - particle
    - particle.converters
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/scikit-hep/particle
  summary: Extended PDG particle data and MC identification codes
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - chrisburr
