{% set name = "particle" %}
{% set version = "0.25.4" %}
{% set python_min = "3.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/particle-{{ version }}.tar.gz
  sha256: bfa77d8aa073e6b498f1ae2d4d4926b707662b060fb23eb986a7cdb4931f58af

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
  run:
    - attrs >=19.2
    - deprecated
    - hepunits >=2.0.0
    - importlib_resources >=2.0
    - python >={{ python_min }}
    - typing-extensions >=4.5

test:
  imports:
    - particle
    - particle.converters
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/scikit-hep/particle
  summary: Extended PDG particle data and MC identification codes
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/scikit-hep/particle

extra:
  recipe-maintainers:
    - eduardo-rodrigues
    - chrisburr
