{% set name = "particle" %}
{% set version = "0.23.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/particle-{{ version }}.tar.gz
  sha256: d810f8fc27deb8e7fd64174017d9607d50522249c0973a0008e580f93db11750

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - hatchling
    - hatch-vcs
  run:
    - attrs >=19.2
    - deprecated
    - hepunits >=2.0.0
    - importlib_resources >=2.0
    - python >=3.7
    - typing-extensions

test:
  imports:
    - particle
    - particle.converters
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/scikit-hep/particle
  summary: Extended PDG particle data and MC identification codes
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - eduardo-rodrigues
    - chrisburr
